<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Fundamentos JavaScript Manejo de errores</title>

    </head>


    <body>
        <h1>Fundamentos de JavaScript manejo de errorres</h1>
        <script>
            // Estructuras de control ciclos o bucles 
            
            // bucle while

            const numeros =[1,2,3,4,5,6,7,8,9,10];

            for(let i=0; i<numeros.length;i++){
                if(i===5){
                    console.log("SE cumple la condición");
                    break;
                }

                console.log(numeros[i])
            }

            const numeros2 =[1,2,3,4,5,6,7,8,9,10];

            for(let i=0; i<numeros2.length;i++){
            if(i===5){
                console.log("SE cumple la condición");
                continue;
            }

    console.log(numeros[i])
}

try {
    console.log("Try se agrega el codigo a evaluar");
    noExiste
} catch (error) {
    console.log('Catch, captura cualquier error serguido o lanzado en el try');
    console.log(error);
}finally{
console.log('este bloque finally se ejecuta siempre al final de un bloque try catch');
}

try {
    let numero=i;
    if(isNaN(numero)){
        throw new Error('El caracter introducido no es un número');
    }
    console.log(numero*numero);
} catch (error) {
    console.log(`Se produjo el siguiente error: ${error}`);
}

        </script>




    </body>


</html>